---
# tasks file for kubernetes install

# Install Kubernetes
- name: "Kubeadm init --pod-network-cidr=192.168.0.0/16"
  shell: |
    kubeadm init --pod-network-cidr=100.64.0.0/16 #--kubernetes-version=v1.15.5
  become: true

# Install calico network
- name: "Install Calico network"
  shell: |
    kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true

# Allow pod deployments on master node
- name: "Allow pod deployments on master node."
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/master-
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true

# Deploy metrics
- name: "Deploy metrics."
  shell: 
    cmd: |
      kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/aggregated-metrics-reader.yaml
      kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/auth-delegator.yaml
      kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/auth-reader.yaml
      kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-apiservice.yaml
      kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-server-service.yaml
      kubectl create -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/deploy/1.8%2B/resource-reader.yaml
      curl -s https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-server-deployment.yaml | sed 's#imagePullPolicy: Always#imagePullPolicy: Always\n        args:\n        - --kubelet-insecure-tls\n        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname#g;' | kubectl apply -f -
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  become: true

# Copy Kubernetes admin credentials
- include: copy-credentials.yml
  loop: "{{ accounts }}"
  
# Add stuff to .bashrc 
- include: add-to-bashrc.yml
  loop: "{{ accounts }}"


